events {
    worker_connections 1024;
}


http {
    include       mime.types;          
    default_type  application/octet-stream;

    upstream backend_servers {
        server theater-moviebooking-1:8000;
        server theater-moviebooking-2:8000;
        server theater-moviebooking-3:8000;
    }

    server {
        listen 80;
        server_name hema;
        server_name localhost;
        server_name hema localhost HemaTheater.com www.HemaTheater.com;
        

        location / {                                        
            proxy_pass http://backend_servers;              
            proxy_set_header Host              $host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        }
    }                                                      
}
